spring:
  application:
    name: KafkaListenerService
  data:
    redis:
      host: localhost
      port: 6379

kafkaprops:
  topic-name: "default"
  cluster-id: "default"
sensorprops:
  uuid: "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"
  name: "default"